### ISSUE TITLE
Minor inconsistency in section header: `Guideline: Maximise readability`

### ISSUE THREAD

**Issue by ianyong** [se-edu/se-book#100]
While working on #97, I realised that the section header `Guideline: Maximise readability` under `Implementation > Code quality` does not adhere to the American English spelling of `maximize`. This is inconsistent with the rest of the textbook which uses the American English spelling of words.

[Link to the relevant section in the CS2103T AY20/21 S1 textbook.](https://nus-cs2103-ay2021s1.github.io/website/se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability)

Not making this change in #97 because I am unsure of whether it will break all of the relative links to this section in the repo, as well as the [module-specific textbooks](https://github.com/nus-cs2103/website-base/blob/master/_module-CS2103/textbookTopics.mbdf#L635). If this change is too much effort, feel free to close this issue.

**Comment by damithc** [comment]
Thanks for the bug report @ianyong 
Will consider this in the next semester's edition of the textbook.

**Comment by damithc** [comment]
Fixed in 03042719fe96bb3c2efbf76759513121083ae367
