### ISSUE TITLE
Inconsistency with source material: SLAP

### ISSUE THREAD

**Issue by ianyong** [se-edu/se-book#101]
In the textbook, it is stated that SLAP stands for:
> Single Level of Abstraction Per method

However, the source material, _The Productive Programmer_ by Neal Ford, states the following instead:
> Single Level of Abstraction Principle

Not sure if this is an intentional deviation from the source material since the textbook's version is more descriptive.

[Link to the relevant section in the CS2103T AY20/21 S1 textbook.](https://nus-cs2103-ay2021s1.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard)

**Comment by damithc** [comment]
IIRC, I took the name used by the original author Robert C. Martin (in Clean Code), which is _Single Level of Abstraction Per Function_ and replaced Function with Method to suit Java.
_Single Level of Abstraction Principle_ sounds nicer, but I think _function/method_ is an important part of the technique. Can probably mention both names. Will do so in the next semester version.

**Comment by damithc** [comment]
Fixed.
