### ISSUE TITLE
Search functionality not working

### ISSUE THREAD

**Issue by tlylt** [se-edu/se-book#106]
### Expect
Able to search content via the search box on the top right corner

### Actual
On typing and pressing Enter, nothing happens. As seen from the console:
![image](https://user-images.githubusercontent.com/41845017/116770494-0401f780-aa77-11eb-99c9-d641fb9def03.png)
![image](https://user-images.githubusercontent.com/41845017/116770504-1419d700-aa77-11eb-923a-119afd73ef1a.png)
There seems to be a problem with initializing Algolia.

---
btw prof: is this book still accepting contributions? If yes I am interested to take on some issues and add exercises/content to it over the summer;)

**Comment by damithc** [comment]
Thanks for the bug report @tlylt 
Fixed.
Good to hear you are interested to contribute. Yes, we are accepting contributions. Adding some more exercises can be helpful but I'm not looking to add a lot of exercises either (given that instructors will have other ways of providing exercises such as tutorial classes)
