### ISSUE TITLE
Contribution guideline?

### ISSUE THREAD

**Issue by tlylt** [se-edu/se-book#107]
Hi Prof, noted your reply on adding exercises and will not be doing it then.

---
As there are limited issues listed in this repo, I am wondering if there are potential tasks/content that could be done to supplement this textbook further?
Besides the two issues I saw ( #48 microservices architecture and #47 serverless architecture) which I lacked the ability to include, 
I am wondering if it is welcomed to add the following content:
- I thought it might be useful to add in functional programming as part of the textbook, in the same fashion as OOP? 
- Perhaps a bit more elaboration on the topic of refactoring (currently the content is quite brief), such as explaining terms like code smell from the refactoring book by Martin Fowler. 

Just some thoughts that I hope will be helpful for students taking 2103T in the future iterations. Please forgive me for intruding and close this issue if it is not in line with the goals of this book.

**Comment by damithc** [comment]
@tlylt No plans to add FP as none of the modules using this textbook ATM needs it.

Yes, I don't mind adding a brief mention of the term _code smells_.

I'm also looking to improve AB3 code/documentation https://github.com/se-edu/addressbook-level3/issues
