### ISSUE TITLE
Side navigation bar closing at 'usage' page 

### ISSUE THREAD

**Issue by FergusMok** [se-edu/se-book#112]
The side navigation bar closes when pressing "How to use this book".
The expected behavior would be for the side bar to remain open, with the current topic highlighted.

Expected Behavior:
![SEBookExpectedBehaviorGif](https://user-images.githubusercontent.com/10182564/146635412-63ba83d8-9f63-485c-b822-89aad17891a3.gif)

Current Behavior: 
![SEBookGif](https://user-images.githubusercontent.com/10182564/146635220-675ae4d4-b36f-4551-a2ff-3a89b524525b.gif)

Removing the popover elements within the page solves the problem temporarily.

**Comment by damithc** [comment]
@FergusMok Thanks for this info. This is actually a MarkBind issue. We were wondering what exactly is causing this problem. As per your info, it seems it's something to do with popovers.

Probably related to https://github.com/MarkBind/markbind/issues/1615
Will post it there.
