### ISSUE TITLE
Conditional "OR" operator formatting is broken on the CS2113 website under the cppToJava section

### ISSUE THREAD

**Issue by Bawfen** [se-edu/se-book#114]
I noticed that the format of the conditional operator is broken on the CS2113 website (https://nus-cs2113-ay2223s2.github.io/website/se-book-adapted/chapters/cppToJava.html#operators).

<img width="718" alt="Screenshot 2023-05-01 at 12 56 10 PM" src="https://user-images.githubusercontent.com/5654392/235408769-b8bfefc2-2102-4d7b-8760-4bb1a72d7fd5.png">

https://github.com/se-edu/se-book/blob/0086f3799378682bf60cf41e1adc5d0669a801bb/cppToJava/dataTypes/operators/text.md?plain=1#L74

I suspect that the `|` character is being read as a table. We could follow the suggestion from https://stackoverflow.com/questions/17319940/how-to-escape-a-pipe-char-in-a-code-statement-in-a-markdown-table to rectify it.

### Suggested Fix
```
<code>&vert;&vert;</code> | or | <code>true &vert;&vert; false</code> %%{{ icon_output_right }}%% `true` | <code>false &vert;&vert; false</code>  %%{{ icon_output_right }}%% `false`
```

**Comment by damithc** [comment]
Thanks for the fix @Bawfen 
I've fixed it in this repo.
