### ISSUE TITLE
Questions: Remove duplication from answers

### ISSUE THREAD

**Issue by damithc** [se-edu/se-book#40]
The answer can contain just the `a`, `b`, `c` etc.  like so:
```
<panel header=":lock::key: What are the advantages of using use cases (the textual form) for requirements modelling?">
<question>

What are the advantages of using use cases (the textual form) for requirements modelling?

- [ ] a. They can be fairly detailed but still natural enough for users for users to understand and give feedback.
- [ ] b. The UI-independent nature of use case specification allows the system designers more freedom to decide how a functionality is provided to a user.
- [ ] c. Extensions encourage us to consider all situations a software product might face during its operations.
- [ ] d. They encourage us to identify and optimize the typical scenario of usage over exceptional usage scenarios.
- [ ] e. All of the above.
- [ ] f. First three only.

<div slot="answer">

e

</div>
</question>
</panel>
```

**Comment by jamessspanggg** [comment]
This issue no longer occurs @damithc

**Comment by damithc** [comment]
Have you checked all questions?
This is a case of the previous author copy pasting the entire answer instead of just the letter.
i.e.,
current `e. All of the above.`
should be `e`

**Comment by jamessspanggg** [comment]
Ok noted, I only checked through some and thought they were the same. Will check through the text book.

**Comment by jamessspanggg** [comment]
Some answers that shouldn't be included are seen to have ~strikethrough~, should we remove them?

<img width="740" alt="Screen Shot 2020-04-05 at 12 37 14 AM" src="https://user-images.githubusercontent.com/32864116/78456332-99e11c80-76d5-11ea-9169-94101269bb7c.png">

**Comment by damithc** [comment]
> Some answers that shouldn't be included are seen to have ~strikethrough~, should we remove them?

That's still fine because it uses the letter only, not the whole answer.
