### ISSUE TITLE
documentation/guidelines/index.md: Typo

### ISSUE THREAD

**Issue by hwkchia** [se-edu/se-book#44]
Typo in `<include src="./aimforComprehensibility/topicPanel.md" />`

Should be `<include src="./aimForComprehensibility/topicPanel.md" />`

Change lowercase `f` to uppercase `F`.

**Comment by damithc** [comment]
Fixed. I've updated the submodule repo. @hwkchia You need to pull the submodule. The change will be visible to end-users only after your next deploy.
