### ISSUE TITLE
Remove unused TopicToc.md

### ISSUE THREAD

**Issue by damithc** [se-edu/se-book#46]
TopicToc.md at lower level topics don't seem to be used

**Comment by jamessspanggg** [comment]
When you mean lower level topics, do you mean the following?
<img width="277" alt="Screen Shot 2020-04-05 at 2 19 00 AM" src="https://user-images.githubusercontent.com/32864116/78458440-e7fd1c80-76e3-11ea-94c4-f931e42d6d60.png">

**Comment by damithc** [comment]
It refers to `topicToc.md` files. It is used only for the following popover, and those are there for the top level topics.
![image](https://user-images.githubusercontent.com/1673303/78469617-89708680-7755-11ea-86fa-a9aee6fbbbe8.png)

In fact, I don't mind getting rid of those popovers as well all `topicToc.md` files can be removed with it.

**Comment by damithc** [comment]
The `preview.md` is another file that can be removed.

**Comment by jamessspanggg** [comment]
So basically, 
- all popovers in all `topicToc.md` should be removed. 
- all `preview.md` should be removed as popovers no longer used.

As for removing unused `topicToc.md`, may I get an example from which topic it should be removed? I can't find any that is unused tho.

**Comment by damithc** [comment]
> As for removing unused `topicToc.md`, may I get an example from which topic it should be removed? I can't find any that is unused tho.

We can remove all those files. `[root]/index.md` is the only place they are used. Instead of including topicToc.md in that page, we can just put the actual content (which is just one bullet point anyway).

**Comment by jamessspanggg** [comment]
> We can remove all those files. [root]/index.md is the only place they are used. Instead of including topicToc.md in that page, we can just put the actual content (which is just one bullet point anyway).

Ok noted.
