### ISSUE TITLE
Use sentence case for headings

### ISSUE THREAD

**Issue by damithc** [se-edu/se-book#52]
As recommended by [Google documentation guidelines](https://developers.google.com/style)

**Comment by Tejas2805** [comment]
![Screen Shot 2020-04-16 at 1 06 10 PM](https://user-images.githubusercontent.com/35946746/79416833-30b9ad00-7fe3-11ea-935b-f87b23076ee5.png)

I just wish to confirm before I work on it - By headings do you refer to page headings or section headings? Or both?

**Comment by damithc** [comment]
> I just wish to confirm before I work on it - By headings do you refer to page headings or section headings? Or both?

We can follow the [Google Documentation Style Guide](https://developers.google.com/style) when deciding this too.
