### ISSUE TITLE
Add a site nav bar

### ISSUE THREAD

**Issue by damithc** [se-edu/se-book#57]
Can be similar to this:
![image](https://user-images.githubusercontent.com/1673303/43694307-4f1c876a-9965-11e8-9c9a-eea8c594abc5.png)

Screenshot from https://nus-cs2103.github.io/website-base/se-book-adapted/

**Comment by Tejas2805** [comment]
Is this issue still open? I would like to try this

**Comment by damithc** [comment]
> Is this issue still open? I would like to try this

Sure, go ahead.
