### ISSUE TITLE
Empty review section for Integration chapter

### ISSUE THREAD

**Issue by jamessspanggg** [se-edu/se-book#72]
[Link to reproduce](https://se-education.org/se-book/integration/)

<img width="1780" alt="Screen Shot 2020-04-05 at 1 27 38 AM" src="https://user-images.githubusercontent.com/32864116/78457424-b2086a00-76dc-11ea-8f82-e6d9e6b80723.png">

**Comment by damithc** [comment]
Can remove if there is no actual content i.e.,  the content was never added in the first place.
