### ISSUE TITLE
Empty titles in learning outcomes

### ISSUE THREAD

**Issue by jamessspanggg** [se-edu/se-book#74]
<img width="1764" alt="Screen Shot 2020-04-05 at 11 05 47 AM" src="https://user-images.githubusercontent.com/32864116/78465875-98dbd980-772d-11ea-8ecd-93789968ac4b.png">

**Comment by damithc** [comment]
Probably I forgot to specify the LO for some of the topics. Whoever is taking the issue can propose LOs for those topics first and I can suggest how to revise each, if needed.

**Comment by jamessspanggg** [comment]
I found out that there is a pattern where the panels with empty titles are actually of the same section as the last panel above with non empty title..

For example, as u can see the last non-empty panel is about readability. The panels below it that have empty titles are actually of under the same content (aka readability), but in different sections of readability.

<img width="930" alt="Screen Shot 2020-04-05 at 11 59 08 AM" src="https://user-images.githubusercontent.com/32864116/78466561-edcf1e00-7734-11ea-801c-9ee31ca94f8d.png">

**Comment by damithc** [comment]
I see. I need time to look into it.

**Comment by damithc** [comment]
Replace this
```html
<include src="../codeQuality/maximiseReadability/basic/unit-inParent-asOutcome.md" boilerplate />
<include src="../codeQuality/maximiseReadability/intermediate/unit-inParent-asOutcome.md" boilerplate />
<include src="../codeQuality/maximiseReadability/advanced/unit-inParent-asOutcome.md" boilerplate />
```
with next level LOs e.g.,
```html
<include src="../codeQuality/maximiseReadability/basic/avoidComplicatedExpressions/unit-inParent-asOutcome.md" boilerplate />
...
```
