### ISSUE TITLE
Dead link in full printable textbook

### ISSUE THREAD

**Issue by jamessspanggg** [se-edu/se-book#81]
In the full printable textbook, the `java` does not link to any of the sections. Perhaps it should link to the `c++ to java` content instead? If that is the case, the `c++ to java` chapter should be under supplementary.

Also, should the `Principles` chapter be under a `Principles` to match with the siteNav as shown on the left?

<img width="932" alt="Screen Shot 2020-04-10 at 8 28 59 PM" src="https://user-images.githubusercontent.com/32864116/78990841-10649b00-7b6a-11ea-9e41-be27abf15496.png">

**Comment by jamessspanggg** [comment]
@damithc need your comment on this.

**Comment by jamessspanggg** [comment]
There is also an empty `java` section in the learning outcomes: https://deploy-preview-80--se-edu-se-book.netlify.com/common/outcomes.html#java

<img width="996" alt="Screen Shot 2020-04-10 at 9 00 23 PM" src="https://user-images.githubusercontent.com/32864116/78992662-57ed2600-7b6e-11ea-9467-4b0731f02a8f.png">

**Comment by damithc** [comment]
Can remove the Java section. It used to contain some Java topics but they have been moved to 'C++ to Java' which will stay as a supplementary topic rather than part of the main topics.
Can tweak the printable version to match the normal version.

**Comment by jamessspanggg** [comment]
> Can remove the Java section.

Noted.

> Can tweak the printable version to match the normal version.

Should I add the `c++ to java` section as a supplementary topic in the printable version?

**Comment by damithc** [comment]
> Should I add the `c++ to java` section as a supplementary topic in the printable version?

Sure.
