### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by aizatazhar** [se-edu/se-book#94]
Hello, I spotted some typos and have linked the relevant code

In [W1.1e exercise](https://github.com/se-edu/se-book/blob/8bf397fe8af8c5b23754f7d258fac3757a698e45/oop/classes/what/q-essay-identifyClassesAndObjects.md), `checqueJohnGave` should be `chequeJohnGave`

In [W1.3d](https://github.com/se-edu/se-book/blob/8bf397fe8af8c5b23754f7d258fac3757a698e45/cppToJava/inheritance/abstractClassesAndMethods/text.md) `the subclass should provides implementations` should be `the subclass should provide implementations`

In [W1.3h](https://github.com/se-edu/se-book/blob/8bf397fe8af8c5b23754f7d258fac3757a698e45/oop/inheritance/dynamicAndStaticBinding/text.md), `calcuateGrade` should be `calculateGrade`

In [Week 3 Project A-Jar](https://github.com/se-edu/se-book/blob/8bf397fe8af8c5b23754f7d258fac3757a698e45/projectDuke/extensions.mbdf), `In the page where you fill the details of th release` should be `In the page where you fill the details of the release`

In [W4.5a](https://github.com/se-edu/se-book/blob/master/cppToJava/misc/varargs/text.md) `allows writing a methods` should be `allows writing a method`

In [W5.3e](https://github.com/se-edu/se-book/blob/master/specifyingRequirements/userStories/usage/text.md) `Step 4: List the user stories to supports the scenarios:` should be `Step 4: List the user stories to support the scenarios:`

In [UML minimal notation diagram](https://github.com/se-edu/se-book/blob/master/uml/sequenceDiagrams/minimalNotation/images/textLogic.png) `get minefiled info` should be `get minefield info`

In [W7.2n](https://github.com/se-edu/se-book/blob/master/designApproaches/topDownBottomUp/what/text.md) `designing a variations` should be either `designing a variation` or `designing variations`

In [W7.5C on the website](https://nus-cs2103-ay2021s1.github.io/website/schedule/week7/topics.html#W7-5) (`stubs`) does not show tooltip when hovering over the text. Relevant code found [here](https://github.com/se-edu/se-book/blob/master/integration/approaches/topDownVsBottomUp/text.md)

In [W7.7c](https://github.com/se-edu/se-book/blob/master/revisionControl/drcsVsCrcs/text.md) `Centralized RCS (CRCS for short)uses` should be `Centralized RCS (CRCS for short) uses` (missing whitespace)

**Comment by damithc** [comment]
> In [W7.5C on the website](https://nus-cs2103-ay2021s1.github.io/website/schedule/week7/topics.html#W7-5) (`stubs`) does not show tooltip when hovering over the text. Relevant code found [here](https://github.com/se-edu/se-book/blob/master/integration/approaches/topDownVsBottomUp/text.md)

Thanks for the detailed bug report @aizatazhar All will be fixed in the next update except the one above, which is a bug in the MarkBind tool, to be fixed soon.
