### ISSUE TITLE
Inconsistency in Object Oriented Domain Models example

### ISSUE THREAD

**Issue by ianyong** [se-edu/se-book#99]
Under `Design > Modeling > Modeling structures > Object Oriented Domain Models`, the example of the OODM for the snakes and ladders game states:

> The above OO domain model omits the ladder class for simplicity. It can be included in a similar fashion to the Snake class.

However, the `Ladder` class is not omitted from the OODM.

![](https://nus-cs2103-ay2021s1.github.io/website/book/modeling/modelingStructures/objectOrientedDomainModels/images/diagram.png)

[Link to the relevant section in the CS2103T AY20/21 S1 textbook.](https://nus-cs2103-ay2021s1.github.io/website/se-book-adapted/chapters/modeling.html#object-oriented-domain-models)

**Comment by damithc** [comment]
Yup. Good catch @ianyong 
Will remove ~~The above OO domain model omits the ladder class for simplicity. It can be included in a similar fashion to the Snake class.~~ in the next update.

**Comment by damithc** [comment]
Fixed.
